---
application:
  name: "bettercnrtl"
  project: "bettercnrtl"
  organization: "QoveryCommunity"
routers:
- name: "main-bettercnrtl"
  routes:
  - application_name: "bettercnrtl"
    paths:
    - "/*"
